spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weather
    username: root
    password: weather
    driver-class-name: org.mariadb.jdbc.Driver
  server.port : 8080
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  liquibase:
    contexts: local
    
logging:
  level:
    ROOT: INFO
    pmb.weatherwatcher: DEBUG
