spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/weather
    username: root
    password: Mariadb_690
    driver-class-name: org.mariadb.jdbc.Driver
  server.port : 7878
management:
  endpoint.health.show-details: WHEN_AUTHORIZED
