server.port: 7878
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weather
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  liquibase:
    drop-first: true
    contexts: local

logging:
  level:
    ROOT: INFO
    pmb.weatherwatcher: DEBUG

jwt.duration: 2592000 # 30j ( -> secondes)