name: Deploy

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: 69pmb/deploy/workflow/deploy@main
        with:
          url: ${{ secrets.DEPLOY_URL }}
          args: "WEATHERAPI_APIKEY,${{ secrets.WEATHERAPI_APIKEY }}@WEBPUSH_PUBLICKEY,${{ secrets.WEBPUSH_PUBLICKEY }}@WEBPUSH_PRIVATEKEY,${{ secrets.WEBPUSH_PRIVATEKEY }}"
